name: Build-CI
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag Name'     
        required: true
       # default: 'latest'
      archName:
        description: architecture must be one of `arm` or `amd`
        required: false

jobs:

  build:
    name: ci-image-build
    
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the latest loxilb Docker image
      if: github.event.inputs.tagName == ''
      run: docker build . --tag ghcr.io/jamroks/loxilb:latest
      
    - name: Build the loxilb Docker image with given tag
      if: github.event.inputs.tagName != ''
      run: docker build . --tag ghcr.io/jamroks/loxilb:${{ github.event.inputs.tagName }}

    - name: Build the loxilb ARM Docker image with given tag
      if: |
          github.event.inputs.tagName != ''
          && github.event.inputs.archName == 'arm'
      run: docker buildx build --platform linux/arm64 --tag ghcr.io/jamroks/loxilb-${{ github.event.inputs.archName }}:${{ github.event.inputs.tagName }} .
      
    - name: Run the loxilb docker image to check
      run: docker run -u root --cap-add SYS_ADMIN  --restart unless-stopped --privileged -dit -v /dev/log:/dev/log --name loxilb ghcr.io/jamroks/loxilb:latest
        
    - name: Publish the latest loxilb Docker image
      if: | 
          github.repository == 'jamroks/loxilb' 
          &&  github.event.inputs.tagName == ''
      run: docker push ghcr.io/jamroks/loxilb:latest
      
    - name: Publish the loxilb ARM Docker image with given tag
      if: |
          github.repository == 'jamroks/loxilb'
          &&  github.event.inputs.tagName != '' 
          && github.event.inputs.archName == 'arm' 
      run: docker push ghcr.io/jamroks/loxilb-${{ github.event.inputs.archName }}:${{ github.event.inputs.tagName }} 
      
    # This is currently not supported yet for docker packages
    - name: Cleanup old Docker packages
      uses: actions/delete-package-versions@v3
      with:
          package-name: 'loxilb'
          num-old-versions-to-delete: 3
